name: dds_service_extensions
description: >-
  Extension methods for `package:vm_service`, used to make requests a
  Dart Development Service (DDS) instance.

version: 1.3.0

homepage: https://github.com/dart-lang/sdk/tree/master/pkg/dds_service_extensions

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
   async: ^2.4.1
   vm_service: ^8.1.0

dev_dependencies:
  lints: ^1.0.0
