linter:
  rules:
    - camel_case_types

analyzer:
  errors:
    unused_element: error
    unused_field: error
    unused_local_variable: error
  exclude:
    - test/res/**
    - test/out/**
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
